// Core database types (will be generated by Prisma)
export interface Client {
  id: string;
  name: string;
  email: string;
  phone?: string;
  billing_address?: string;
  notes?: string;
  created_at: Date;
  updated_at: Date;
}

export interface Invoice {
  id: string;
  client_id: string;
  invoice_number: string;
  status: InvoiceStatus;
  total_amount: number;
  sent_date?: Date;
  due_date?: Date;
  paid_date?: Date;
  created_at: Date;
  updated_at: Date;
  client?: Client;
  items?: InvoiceItem[];
}

export interface InvoiceItem {
  id: string;
  invoice_id: string;
  description: string;
  quantity: number;
  rate: number;
  total: number;
  created_at: Date;
}

// Enums
export enum InvoiceStatus {
  DRAFT = 'draft',
  SENT = 'sent',
  PAID = 'paid',
  OVERDUE = 'overdue'
}

export enum RecurrenceFrequency {
  WEEKLY = 'weekly',
  MONTHLY = 'monthly',
  QUARTERLY = 'quarterly',
  YEARLY = 'yearly'
}

// Form types
export interface ClientFormData {
  name: string;
  email: string;
  phone?: string;
  billing_address?: string;
  notes?: string;
}

export interface InvoiceFormData {
  client_id: string;
  due_date?: string;
  items: InvoiceItemFormData[];
}

export interface InvoiceItemFormData {
  description: string;
  quantity: number;
  rate: number;
}

// API response types
export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
}

// Authentication types
export interface AuthSession {
  isAuthenticated: boolean;
  user?: {
    username: string;
  };
}

export interface LoginCredentials {
  username: string;
  password: string;
}

// Email types
export interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  attachments?: Array<{
    filename: string;
    content: Buffer;
    contentType: string;
  }>;
}

// PDF generation types
export interface InvoicePDFData {
  invoice: Invoice & {
    client: Client;
    items: InvoiceItem[];
  };
  company: {
    name: string;
    email: string;
    address?: string;
    phone?: string;
  };
}

// Search and filter types
export interface ClientFilters {
  search?: string;
  page?: number;
  limit?: number;
}

export interface InvoiceFilters {
  search?: string;
  status?: InvoiceStatus;
  client_id?: string;
  date_from?: string;
  date_to?: string;
  page?: number;
  limit?: number;
}

// Utility types
export type CreateClientData = Omit<Client, 'id' | 'created_at' | 'updated_at'>;
export type UpdateClientData = Partial<CreateClientData>;
export type CreateInvoiceData = Omit<Invoice, 'id' | 'invoice_number' | 'created_at' | 'updated_at'>;
export type UpdateInvoiceData = Partial<CreateInvoiceData>; 